// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"nodepad-be/ent/note"
	"nodepad-be/ent/user"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// NoteCreate is the builder for creating a Note entity.
type NoteCreate struct {
	config
	mutation *NoteMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *NoteCreate) SetDeletedAt(v time.Time) *NoteCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *NoteCreate) SetNillableDeletedAt(v *time.Time) *NoteCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *NoteCreate) SetUserID(v uuid.UUID) *NoteCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *NoteCreate) SetNillableUserID(v *uuid.UUID) *NoteCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetShareKey sets the "share_key" field.
func (_c *NoteCreate) SetShareKey(v string) *NoteCreate {
	_c.mutation.SetShareKey(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *NoteCreate) SetTitle(v string) *NoteCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_c *NoteCreate) SetNillableTitle(v *string) *NoteCreate {
	if v != nil {
		_c.SetTitle(*v)
	}
	return _c
}

// SetContent sets the "content" field.
func (_c *NoteCreate) SetContent(v string) *NoteCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_c *NoteCreate) SetNillableContent(v *string) *NoteCreate {
	if v != nil {
		_c.SetContent(*v)
	}
	return _c
}

// SetCreatedAt sets the "createdAt" field.
func (_c *NoteCreate) SetCreatedAt(v time.Time) *NoteCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (_c *NoteCreate) SetNillableCreatedAt(v *time.Time) *NoteCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updatedAt" field.
func (_c *NoteCreate) SetUpdatedAt(v time.Time) *NoteCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updatedAt" field if the given value is not nil.
func (_c *NoteCreate) SetNillableUpdatedAt(v *time.Time) *NoteCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *NoteCreate) SetID(v uuid.UUID) *NoteCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *NoteCreate) SetNillableID(v *uuid.UUID) *NoteCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *NoteCreate) SetUser(v *User) *NoteCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the NoteMutation object of the builder.
func (_c *NoteCreate) Mutation() *NoteMutation {
	return _c.mutation
}

// Save creates the Note in the database.
func (_c *NoteCreate) Save(ctx context.Context) (*Note, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NoteCreate) SaveX(ctx context.Context) *Note {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NoteCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NoteCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *NoteCreate) defaults() error {
	if _, ok := _c.mutation.Content(); !ok {
		v := note.DefaultContent
		_c.mutation.SetContent(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if note.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized note.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := note.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if note.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized note.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := note.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		if note.DefaultID == nil {
			return fmt.Errorf("ent: uninitialized note.DefaultID (forgotten import ent/runtime?)")
		}
		v := note.DefaultID()
		_c.mutation.SetID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *NoteCreate) check() error {
	if _, ok := _c.mutation.ShareKey(); !ok {
		return &ValidationError{Name: "share_key", err: errors.New(`ent: missing required field "Note.share_key"`)}
	}
	if v, ok := _c.mutation.ShareKey(); ok {
		if err := note.ShareKeyValidator(v); err != nil {
			return &ValidationError{Name: "share_key", err: fmt.Errorf(`ent: validator failed for field "Note.share_key": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := note.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Note.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "Note.content"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "createdAt", err: errors.New(`ent: missing required field "Note.createdAt"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updatedAt", err: errors.New(`ent: missing required field "Note.updatedAt"`)}
	}
	return nil
}

func (_c *NoteCreate) sqlSave(ctx context.Context) (*Note, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NoteCreate) createSpec() (*Note, *sqlgraph.CreateSpec) {
	var (
		_node = &Note{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(note.Table, sqlgraph.NewFieldSpec(note.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(note.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = value
	}
	if value, ok := _c.mutation.ShareKey(); ok {
		_spec.SetField(note.FieldShareKey, field.TypeString, value)
		_node.ShareKey = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(note.FieldTitle, field.TypeString, value)
		_node.Title = &value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(note.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(note.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(note.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   note.UserTable,
			Columns: []string{note.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Note.Create().
//		SetDeletedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NoteUpsert) {
//			SetDeletedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *NoteCreate) OnConflict(opts ...sql.ConflictOption) *NoteUpsertOne {
	_c.conflict = opts
	return &NoteUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Note.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *NoteCreate) OnConflictColumns(columns ...string) *NoteUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &NoteUpsertOne{
		create: _c,
	}
}

type (
	// NoteUpsertOne is the builder for "upsert"-ing
	//  one Note node.
	NoteUpsertOne struct {
		create *NoteCreate
	}

	// NoteUpsert is the "OnConflict" setter.
	NoteUpsert struct {
		*sql.UpdateSet
	}
)

// SetDeletedAt sets the "deleted_at" field.
func (u *NoteUpsert) SetDeletedAt(v time.Time) *NoteUpsert {
	u.Set(note.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *NoteUpsert) UpdateDeletedAt() *NoteUpsert {
	u.SetExcluded(note.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *NoteUpsert) ClearDeletedAt() *NoteUpsert {
	u.SetNull(note.FieldDeletedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *NoteUpsert) SetUserID(v uuid.UUID) *NoteUpsert {
	u.Set(note.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *NoteUpsert) UpdateUserID() *NoteUpsert {
	u.SetExcluded(note.FieldUserID)
	return u
}

// ClearUserID clears the value of the "user_id" field.
func (u *NoteUpsert) ClearUserID() *NoteUpsert {
	u.SetNull(note.FieldUserID)
	return u
}

// SetTitle sets the "title" field.
func (u *NoteUpsert) SetTitle(v string) *NoteUpsert {
	u.Set(note.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *NoteUpsert) UpdateTitle() *NoteUpsert {
	u.SetExcluded(note.FieldTitle)
	return u
}

// ClearTitle clears the value of the "title" field.
func (u *NoteUpsert) ClearTitle() *NoteUpsert {
	u.SetNull(note.FieldTitle)
	return u
}

// SetContent sets the "content" field.
func (u *NoteUpsert) SetContent(v string) *NoteUpsert {
	u.Set(note.FieldContent, v)
	return u
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *NoteUpsert) UpdateContent() *NoteUpsert {
	u.SetExcluded(note.FieldContent)
	return u
}

// SetUpdatedAt sets the "updatedAt" field.
func (u *NoteUpsert) SetUpdatedAt(v time.Time) *NoteUpsert {
	u.Set(note.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updatedAt" field to the value that was provided on create.
func (u *NoteUpsert) UpdateUpdatedAt() *NoteUpsert {
	u.SetExcluded(note.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Note.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(note.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *NoteUpsertOne) UpdateNewValues() *NoteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(note.FieldID)
		}
		if _, exists := u.create.mutation.ShareKey(); exists {
			s.SetIgnore(note.FieldShareKey)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(note.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Note.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *NoteUpsertOne) Ignore() *NoteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NoteUpsertOne) DoNothing() *NoteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NoteCreate.OnConflict
// documentation for more info.
func (u *NoteUpsertOne) Update(set func(*NoteUpsert)) *NoteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NoteUpsert{UpdateSet: update})
	}))
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *NoteUpsertOne) SetDeletedAt(v time.Time) *NoteUpsertOne {
	return u.Update(func(s *NoteUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *NoteUpsertOne) UpdateDeletedAt() *NoteUpsertOne {
	return u.Update(func(s *NoteUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *NoteUpsertOne) ClearDeletedAt() *NoteUpsertOne {
	return u.Update(func(s *NoteUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *NoteUpsertOne) SetUserID(v uuid.UUID) *NoteUpsertOne {
	return u.Update(func(s *NoteUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *NoteUpsertOne) UpdateUserID() *NoteUpsertOne {
	return u.Update(func(s *NoteUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *NoteUpsertOne) ClearUserID() *NoteUpsertOne {
	return u.Update(func(s *NoteUpsert) {
		s.ClearUserID()
	})
}

// SetTitle sets the "title" field.
func (u *NoteUpsertOne) SetTitle(v string) *NoteUpsertOne {
	return u.Update(func(s *NoteUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *NoteUpsertOne) UpdateTitle() *NoteUpsertOne {
	return u.Update(func(s *NoteUpsert) {
		s.UpdateTitle()
	})
}

// ClearTitle clears the value of the "title" field.
func (u *NoteUpsertOne) ClearTitle() *NoteUpsertOne {
	return u.Update(func(s *NoteUpsert) {
		s.ClearTitle()
	})
}

// SetContent sets the "content" field.
func (u *NoteUpsertOne) SetContent(v string) *NoteUpsertOne {
	return u.Update(func(s *NoteUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *NoteUpsertOne) UpdateContent() *NoteUpsertOne {
	return u.Update(func(s *NoteUpsert) {
		s.UpdateContent()
	})
}

// SetUpdatedAt sets the "updatedAt" field.
func (u *NoteUpsertOne) SetUpdatedAt(v time.Time) *NoteUpsertOne {
	return u.Update(func(s *NoteUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updatedAt" field to the value that was provided on create.
func (u *NoteUpsertOne) UpdateUpdatedAt() *NoteUpsertOne {
	return u.Update(func(s *NoteUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *NoteUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NoteCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NoteUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *NoteUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: NoteUpsertOne.ID is not supported by MySQL driver. Use NoteUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *NoteUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// NoteCreateBulk is the builder for creating many Note entities in bulk.
type NoteCreateBulk struct {
	config
	err      error
	builders []*NoteCreate
	conflict []sql.ConflictOption
}

// Save creates the Note entities in the database.
func (_c *NoteCreateBulk) Save(ctx context.Context) ([]*Note, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Note, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NoteMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NoteCreateBulk) SaveX(ctx context.Context) []*Note {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NoteCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NoteCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Note.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NoteUpsert) {
//			SetDeletedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *NoteCreateBulk) OnConflict(opts ...sql.ConflictOption) *NoteUpsertBulk {
	_c.conflict = opts
	return &NoteUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Note.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *NoteCreateBulk) OnConflictColumns(columns ...string) *NoteUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &NoteUpsertBulk{
		create: _c,
	}
}

// NoteUpsertBulk is the builder for "upsert"-ing
// a bulk of Note nodes.
type NoteUpsertBulk struct {
	create *NoteCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Note.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(note.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *NoteUpsertBulk) UpdateNewValues() *NoteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(note.FieldID)
			}
			if _, exists := b.mutation.ShareKey(); exists {
				s.SetIgnore(note.FieldShareKey)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(note.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Note.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *NoteUpsertBulk) Ignore() *NoteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NoteUpsertBulk) DoNothing() *NoteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NoteCreateBulk.OnConflict
// documentation for more info.
func (u *NoteUpsertBulk) Update(set func(*NoteUpsert)) *NoteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NoteUpsert{UpdateSet: update})
	}))
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *NoteUpsertBulk) SetDeletedAt(v time.Time) *NoteUpsertBulk {
	return u.Update(func(s *NoteUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *NoteUpsertBulk) UpdateDeletedAt() *NoteUpsertBulk {
	return u.Update(func(s *NoteUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *NoteUpsertBulk) ClearDeletedAt() *NoteUpsertBulk {
	return u.Update(func(s *NoteUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *NoteUpsertBulk) SetUserID(v uuid.UUID) *NoteUpsertBulk {
	return u.Update(func(s *NoteUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *NoteUpsertBulk) UpdateUserID() *NoteUpsertBulk {
	return u.Update(func(s *NoteUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *NoteUpsertBulk) ClearUserID() *NoteUpsertBulk {
	return u.Update(func(s *NoteUpsert) {
		s.ClearUserID()
	})
}

// SetTitle sets the "title" field.
func (u *NoteUpsertBulk) SetTitle(v string) *NoteUpsertBulk {
	return u.Update(func(s *NoteUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *NoteUpsertBulk) UpdateTitle() *NoteUpsertBulk {
	return u.Update(func(s *NoteUpsert) {
		s.UpdateTitle()
	})
}

// ClearTitle clears the value of the "title" field.
func (u *NoteUpsertBulk) ClearTitle() *NoteUpsertBulk {
	return u.Update(func(s *NoteUpsert) {
		s.ClearTitle()
	})
}

// SetContent sets the "content" field.
func (u *NoteUpsertBulk) SetContent(v string) *NoteUpsertBulk {
	return u.Update(func(s *NoteUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *NoteUpsertBulk) UpdateContent() *NoteUpsertBulk {
	return u.Update(func(s *NoteUpsert) {
		s.UpdateContent()
	})
}

// SetUpdatedAt sets the "updatedAt" field.
func (u *NoteUpsertBulk) SetUpdatedAt(v time.Time) *NoteUpsertBulk {
	return u.Update(func(s *NoteUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updatedAt" field to the value that was provided on create.
func (u *NoteUpsertBulk) UpdateUpdatedAt() *NoteUpsertBulk {
	return u.Update(func(s *NoteUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *NoteUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the NoteCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NoteCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NoteUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
