// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	auth "nodepad-be/internal/handler/auth"
	note "nodepad-be/internal/handler/note"
	"nodepad-be/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/auth/login",
				Handler: auth.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/auth/logout",
				Handler: auth.LogoutHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/auth/register",
				Handler: auth.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CookieAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/auth/me",
					Handler: auth.MeHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/notes",
				Handler: note.CreateNoteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/notes/public/:shareKey",
				Handler: note.GetPublicNoteHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CookieAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/notes",
					Handler: note.GetNotesHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/notes/:id",
					Handler: note.GetNoteHandler(serverCtx),
				},
				{
					Method:  http.MethodPatch,
					Path:    "/notes/:id",
					Handler: note.UpdateNoteHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/notes/:id",
					Handler: note.DeleteNoteHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api"),
	)
}
