upstream backend {
    # ưu tiên những backend ít connect
    # least_conn;
    # ip_hash;
    server 172.31.10.170:8080;
    server 172.31.14.209:8080;
}

server {
        listen 80;
        listen [::]:80;
        server_name load-balancer.vulebaolong.com;
        return 301  https://$host$request_uri;
}

server {
        listen 443 ssl;
        listen [::]:443 ssl;

        server_name load-balancer.vulebaolong.com;

        ssl_certificate /etc/nginx/ssl/vulebaolong.com.crt;
        ssl_certificate_key /etc/nginx/ssl/vulebaolong.com.key;

        location / {
                proxy_pass  http://backend;
                include proxy_params;
        }
}
