// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AuthResponse struct {
	AccessToken string   `json:"accessToken"`
	TokenType   string   `json:"tokenType"`
	ExpiresIn   int64    `json:"expiresIn"`
	User        AuthUser `json:"user"`
}

type AuthUser struct {
	Id        string  `json:"id"`
	Email     string  `json:"email"`
	CreatedAt string  `json:"createdAt"`
	UpdatedAt string  `json:"updatedAt"`
	DeletedAt *string `json:"deletedAt"`
}

type CreateNoteRequest struct {
	Authorization string  `header:"Authorization,optional"`
	Title         *string `json:"title,optional"`
	Content       string  `json:"content"`
}

type DeleteNoteRequest struct {
	Id string `path:"id"`
}

type GetNoteRequest struct {
	Id string `path:"id"`
}

type GetNotesRequest struct {
	Page     int `form:"page,optional"`
	PageSize int `form:"pageSize,optional"`
}

type GetPublicNoteRequest struct {
	ShareKey string `path:"shareKey"`
}

type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type MeResponse struct {
	Id        string  `json:"id"`
	Email     string  `json:"email"`
	CreatedAt string  `json:"createdAt"`
	UpdatedAt string  `json:"updatedAt"`
	DeletedAt *string `json:"deletedAt"`
}

type NoteData struct {
	Id        string  `json:"id"`
	UserId    *string `json:"userId"`
	ShareKey  string  `json:"shareKey"`
	ShareUrl  string  `json:"shareUrl"`
	Title     *string `json:"title"`
	Content   string  `json:"content"`
	CreatedAt string  `json:"createdAt"`
	UpdatedAt string  `json:"updatedAt"`
	DeletedAt *string `json:"deletedAt"`
}

type NoteListResponse struct {
	Page       int        `json:"page"`
	PageSize   int        `json:"pageSize"`
	TotalItems int        `json:"totalItems"`
	TotalPages int        `json:"totalPages"`
	Items      []NoteData `json:"items"`
}

type RegisterRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type UpdateNoteRequest struct {
	Id      string  `path:"id"`
	Title   *string `json:"title,optional"`
	Content *string `json:"content,optional"`
}
