services:
  grafana:
    image: grafana/grafana:13.2.1
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana

  loki:
    image: grafana/loki:3.6.16
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki-data:/tmp/loki

  alloy:
    image: grafana/alloy:v1.19.2
    container_name: alloy
    command: [ run, --storage.path=/var/lib/alloy/data, /etc/alloy/config.alloy ]
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - alloy-data:/var/lib/alloy/data
    depends_on:
      - loki

  prometheus:
    image: prom/prometheus:v3.14.0
    container_name: prometheus
    extra_hosts:
      - "host:host-gateway"
    ports:
      - 9090:9090
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus:/etc/prometheus

  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.12.1
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'

volumes:
  grafana-data:
  loki-data:
  alloy-data:
  prometheus-data:
