name: Deploy

on:
    push:
        branches:
            - main

env:
    IMAGE_NAME: img-nodepad_fe
    IMAGE_TAG: latest
    SERVER_HOST_CONTROL_PLANE: ${{ secrets.SERVER_HOST_CONTROL_PLANE }}
    SERVER_USER: ${{ secrets.SERVER_USER }}
    NODEPAD_TOKEN_DOCKER: ${{ secrets.NODEPAD_TOKEN_DOCKER }}
    NODEPAD_USERNAME_DOCKER: vulebaolong

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout source
              uses: actions/checkout@v4

            - name: Setup SSH agent
              uses: webfactory/ssh-agent@v0.9.0
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Trust deploy host
              run: |
                  mkdir -p ~/.ssh
                  ssh-keyscan -H $SERVER_HOST_CONTROL_PLANE >> ~/.ssh/known_hosts

            - name: Open SSH tunnel
              run: |
                  ssh -f -N \
                    -o ExitOnForwardFailure=yes \
                    -L 5000:127.0.0.1:5000 \
                    $SERVER_USER@$SERVER_HOST_CONTROL_PLANE

            - name: Build Docker image
              run: |
                  docker build \
                  --build-arg NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }} \
                  -t $IMAGE_NAME:$IMAGE_TAG .

            - name: Login to Docker Hub
              uses: docker/login-action@v4
              with:
                  username: ${{ env.NODEPAD_USERNAME_DOCKER }}
                  password: ${{ env.NODEPAD_TOKEN_DOCKER }}
              
            - name: Push Docker image
              run: |
                  docker tag $IMAGE_NAME:$IMAGE_TAG $NODEPAD_USERNAME_DOCKER/$IMAGE_NAME:$IMAGE_TAG
                  docker push $NODEPAD_USERNAME_DOCKER/$IMAGE_NAME:$IMAGE_TAG

            - name: Restart Kubernetes deployment
              run: |
                  ssh "$SERVER_USER@$SERVER_HOST_CONTROL_PLANE" << 'EOF'
                    sudo kubectl rollout restart deployment/nodepad-fe
                    sudo kubectl rollout status deployment/nodepad-fe
                  EOF
