// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"nodepad-be/ent/note"
	"nodepad-be/ent/schema"
	"nodepad-be/ent/user"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	noteMixin := schema.Note{}.Mixin()
	noteMixinHooks0 := noteMixin[0].Hooks()
	note.Hooks[0] = noteMixinHooks0[0]
	note.Hooks[1] = noteMixinHooks0[1]
	noteMixinInters0 := noteMixin[0].Interceptors()
	note.Interceptors[0] = noteMixinInters0[0]
	noteFields := schema.Note{}.Fields()
	_ = noteFields
	// noteDescShareKey is the schema descriptor for share_key field.
	noteDescShareKey := noteFields[2].Descriptor()
	// note.ShareKeyValidator is a validator for the "share_key" field. It is called by the builders before save.
	note.ShareKeyValidator = func() func(string) error {
		validators := noteDescShareKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(share_key string) error {
			for _, fn := range fns {
				if err := fn(share_key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// noteDescTitle is the schema descriptor for title field.
	noteDescTitle := noteFields[3].Descriptor()
	// note.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	note.TitleValidator = noteDescTitle.Validators[0].(func(string) error)
	// noteDescContent is the schema descriptor for content field.
	noteDescContent := noteFields[4].Descriptor()
	// note.DefaultContent holds the default value on creation for the content field.
	note.DefaultContent = noteDescContent.Default.(string)
	// noteDescCreatedAt is the schema descriptor for createdAt field.
	noteDescCreatedAt := noteFields[5].Descriptor()
	// note.DefaultCreatedAt holds the default value on creation for the createdAt field.
	note.DefaultCreatedAt = noteDescCreatedAt.Default.(func() time.Time)
	// noteDescUpdatedAt is the schema descriptor for updatedAt field.
	noteDescUpdatedAt := noteFields[6].Descriptor()
	// note.DefaultUpdatedAt holds the default value on creation for the updatedAt field.
	note.DefaultUpdatedAt = noteDescUpdatedAt.Default.(func() time.Time)
	// note.UpdateDefaultUpdatedAt holds the default value on update for the updatedAt field.
	note.UpdateDefaultUpdatedAt = noteDescUpdatedAt.UpdateDefault.(func() time.Time)
	// noteDescID is the schema descriptor for id field.
	noteDescID := noteFields[0].Descriptor()
	// note.DefaultID holds the default value on creation for the id field.
	note.DefaultID = noteDescID.Default.(func() uuid.UUID)
	userMixin := schema.User{}.Mixin()
	userMixinHooks0 := userMixin[0].Hooks()
	user.Hooks[0] = userMixinHooks0[0]
	user.Hooks[1] = userMixinHooks0[1]
	userMixinInters0 := userMixin[0].Interceptors()
	user.Interceptors[0] = userMixinInters0[0]
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = func() func(string) error {
		validators := userDescEmail.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(email string) error {
			for _, fn := range fns {
				if err := fn(email); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[2].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
	// userDescCreatedAt is the schema descriptor for createdAt field.
	userDescCreatedAt := userFields[3].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the createdAt field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updatedAt field.
	userDescUpdatedAt := userFields[4].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updatedAt field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updatedAt field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}

const (
	Version = "v0.14.6"                                         // Version of ent codegen.
	Sum     = "h1:/f2696BpwuWAEEG6PVGWflg6+Inrpq4pRWuNlWz/Skk=" // Sum of ent codegen.
)
